FROM mysql:latest

CMD ["mysqld"]
# 切换目录
# cd ./thirdpart/mysql
# 构建和运行
# docker build -t mysql-app .
# docker run --name running-mysql-app -v /home/test/mysql-data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD="123456" -p 3306:3306 -p 33060:33060 -d mysql-app
# 进入容器
# docker exec -it running-mysql-app bash
# 停止容器
# docker stop running-mysql-app
# 查看日志
# docker logs running-mysql-app
